version: "2"

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FAAngular
    ports:
      - "4200:4200"
    volumes:
      - .:/home/foodacidity
      - /home/foodacidity/node_modules
